version: '3.2'

services:
  vauboo-db-m1:
    build:
      context: './.docker/db/'
    container_name: vauboo-db-m1
    environment:
      MARIADB_VERSION: ${MARIADB_VERSION}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3699:3306"
    volumes:
      - vauboo-mysql-data:/var/lib/mysql
    networks:
      - vaub_net

  vauboo-php-m1:
    build:
      context: './.docker/phpApache/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: vauboo-php-m1
    depends_on:
      - vauboo-db-m1
    volumes:
      - ../sources:/var/www/html:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
      - ./.docker/phpApache/vhost/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/phpApache/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/phpApache/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "${APACHE_HTTP_PORT}:80"
    stdin_open: true
    tty: true
    networks:
      - vaub_net

  vauboo-redis-m1:
    image: "redis:alpine"
    container_name: vauboo-redis-m1
    networks:
      - vaub_net

networks:
  vaub_net:

volumes:
  vauboo-mysql-data: